project:
  type: book
  resources: images

# this ensures that diagram code (e.g. R/Python/Julia) doesn't run on github.
# That simplifies CI, since we don't need to ensure that the relevant code
# environments are available. Best practice, but probably unnecessary.
execute:
  freeze: auto

book:
  repo-url: https://github.com/Carnap/Carnap-Manual
  repo-actions: [edit, issue]
  title: The Carnap Manual
  author: Graham Leach-Krouse
  date: 7/28/2023
  chapters:
    - index.qmd
    - part: Getting Started
      chapters:
      - quickstart.qmd
      - faq.qmd
      - dashboard.qmd
      - pandoc.qmd
      - awesome-carnap.qmd
    - part: Exercises
      chapters:
      - derivations.qmd
      - truth-tables.qmd
      - translation.qmd
      - modelchecker.qmd
      - gentzen-ND.qmd
      - sequent-calculus.qmd
      - qualitative.qmd
      - truth-tree.qmd
      - syntax-check.qmd
    - part: systems.qmd
      chapters:
        - equivalences.qmd
        - forallx-msu.qmd
        - forallx-pitt.qmd
        - forallx-yyc.qmd
        - forallx.qmd
        - logicbook.qmd
        - montague.qmd
        - Set_Theory_Demo.qmd
    - part: Advanced Usage
      chapters:
      - administration.qmd
      - lti.qmd
      - lti-develop.qmd
      - javascript.qmd
      - installation.qmd
      - api.qmd
      - server-configuration.qmd
    - references.qmd
  sidebar:
    logo: ./images/carnap-logo.png
    collapse-level: 1

bibliography: references.bib

format:
  html:
    filters:
      - ./filters/renderFormulas.lua
      - ./filters/truth-tables.lua
      - ./filters/countermodeler.lua
      - ./filters/syntax-checkers.lua
      - ./filters/tree-deductions.lua
      - ./filters/sequent-deductions.lua
      - ./filters/derivations.lua
      - ./filters/translate.lua
      - ./filters/qualitative.lua
    theme: cosmo
    include-in-header:
      text: |
        <link href="https://fonts.googleapis.com/css?family=Fira+Sans|Open+Sans&display=swap" rel="stylesheet">
        <link rel='stylesheet', type='text/css', href='https://carnap.io/static/css/exercises.css'>
        <link rel='stylesheet', type='text/css', href='https://carnap.io/static/css/tree.css'>
        <link type='text/css' href='https://cdn.jsdelivr.net/gh/gleachkr/ProofJS@gh-pages/proof.css' rel='stylesheet'>
        <!-- ↓ override bootstrap to prevent visual glitches -->
        <style type='text/css'> svg { vertical-align: unset } </style>
        <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
        <script src='https://cdn.jsdelivr.net/npm/popper.js@1.16.0'></script>
        <script src='https://cdn.jsdelivr.net/gh/gleachkr/ProofJS@gh-pages/proof.js'></script>

    include-after-body:
      text: |
        <script defer src='https://carnap.io/static/ghcjs/rts.js'></script>
        <script defer src='https://carnap.io/static/ghcjs/allactions/lib.js'></script>
        <script defer src='https://carnap.io/static/ghcjs/allactions/out.js'></script>
        <script defer src='https://carnap.io/static/ghcjs/allactions/runmain.js'></script>
  pdf:
    documentclass: scrreprt

